[package]
name = "mvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mvim-lsp = { path = "../mvim-lsp" }
mlua = { version = "0.9.2", features = ["luajit", "macros"] }
nvim-oxi = { version = "0.4.1", features = ["neovim-nightly", "libuv", "mlua"] }
