[package]
name = "neovim-config"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[workspace]
members = [
    "xtask"
]

[dependencies]
nvim-oxi = { version = "0.4.1", features = ["neovim-nightly", "libuv", "mlua"] }
