[package]
name = "options"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
nvim-oxi = { version = "0.2.2", features = ["neovim-nightly"] }
