[package]
name = "common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mlua = { version = "0.8.8", features = ["luajit"] }
nvim-oxi = { version = "0.2.2", features = ["neovim-nightly", "mlua"] }
